name    'puppet-hhvm'
version '0.1.0'
source  'git@github.com:tronga/puppet-hhvm.git'
author  'Jan Gantzert'
license 'GPL v3'
summary 'HHVM puppet module for ubuntu'
description 'HHVM puppet module for ubuntu'
project_page 'git@github.com:tronga/puppet-hhvm.git'
dependency 'puppetlabs/apt', '1.2.*'
